# Generated by Django 4.0.5 on 2022-06-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('tage', models.IntegerField(max_length=5)),
                ('tphone', models.BigIntegerField()),
                ('tpswd', models.CharField(max_length=20)),
                ('temail', models.CharField(max_length=50)),
                ('tcity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.IntegerField(max_length=5)),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.course')),
                ('tname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trainerapp.trainer_register')),
            ],
        ),
    ]
